### ISSUE TITLE
Display request header

### ISSUE THREAD

**Issue by Drusy** [JakeWorrell/docodile#1]
Do you plan to add request headers ?
Headers are shown like this in the collection's requests:
```
"header": [
    {
        "key": "Content-Type",
        "value": "application/x-www-form-urlencoded"
    },
    {
        "key": "Accept-Language",
        "value": "fr",
        "disabled": true
    },
    {
        "key": "Authorization",
        "value": "Bearer {{admin_token}}"
    }
]
```

**Comment by JakeWorrell** [comment]
Hello

I must admit, I have left Docodile to stagnate quite a bit and I could probably do with giving it a bit more attention.

Your suggestion sounds like a good one, so I'll consider it a feature request and see if I can find some time to add it in the future. You're welcome of course to fork off a new branch, add the feature and submit a pull request if you have the inclination to do so.

Thanks

**Comment by Drusy** [comment]
I am working on it right now, planning to add the following for myself:
- Displaying headers
- Update the request file to prefix it with the request method allowing to have the same name twice with different methodes

Should I work on two PR or one would be enough ?

**Comment by JakeWorrell** [comment]
One is fine :)

Both great ideas, I look forward to receiving the PR.

**Comment by Drusy** [comment]
Here it is #2 😃

**Comment by JakeWorrell** [comment]
Great stuff @Drusy, tested it with a postman collection for a big project and the output looked great. I have merged the PR into develop.

Thanks very much for your contribution and for using Docodile.
