### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by loretoparisi** [JakeWorrell/docodile#4]
Thanks for this project. I see that now markdown support is not correct, right?

**Comment by JakeWorrell** [comment]
Hi

Unfortunately there is currently no Markdown support in Docodile, but since Postman supports Markdown, it would be a nice feature to add.

**Comment by JakeWorrell** [comment]
Markdown support has now been added for request descriptions. Not all markdown features appear to be working correctly current, but basic formatting and lists are working fine. Will potentially look at further improvements in the future
